name: Build

on: workflow_call

jobs:
  build:
    name: Build & push to GHCR.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repo in lowercase
        id: repo-name
        run: |
          echo "lower-repo=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Generate Docker meta data
        uses: docker/metadata-action@v4
        id: docker-meta
        with:
          images: ghcr.io/${{ steps.repo-name.outputs.lower-repo }}
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo-name.outputs.lower-repo }}
          cache-to: type=inline
          tags: ${{ steps.docker-meta.outputs.tags }}
