name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  build:
    uses: ./.github/workflows/build.yaml
    needs:
      - lint
    secrets: inherit

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yaml
    needs:
      - build
    secrets: inherit
